version: '2'

services:
  web:
    restart: always
    build: ./
    expose:
      - "8000"
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/home/flask/app/backend
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app

#END
